#!/bin/bash
# configure Solr to run on the local interface, and start it running in the background

set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

MY_SOLR_OPTS="$(source /opt/solr/bin/solr.in.sh; echo "$SOLR_OPTS") -Djetty.host=${SOLR_LOCAL_HOST:-localhost}"

echo "Running solr in the background. Logs are in /opt/solr/server/logs"
SOLR_OPTS=$MY_SOLR_OPTS solr start
max_try=${MAX_TRY:-12}
wait_seconds=${WAIT_SECONDS:-5}
if ! /opt/docker-solr/scripts/wait-for-solr.sh "$max_try" "$wait_seconds"; then
    echo "Could not start Solr."
    if [ -f /opt/solr/server/logs/solr.log ]; then
        echo "Here is the log:"
        cat /opt/solr/server/logs/solr.log
    fi
    exit 1
fi
